---
version: "3.8"

services:
  ui:
    build:
      context: src
      target: base
    working_dir: /srv
    command:
      - dumb-init
      - npm
      - run
      - dev
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/credentials.json
      BUCKET_URL: gs://kubeseal-certificates-test
    ports:
      # Main app
      - "3000:3000"
      # Live reload
      - "3001:3001"
    volumes:
      - ./src:/srv
      - ./credentials.json:/var/secrets/google/credentials.json
      - node-modules:/srv/node_modules
      - remix-build:/srv/build
      - remix-cache:/srv/.cache
      - remix-public-build:/srv/public/build

volumes:
  node-modules:
  remix-build:
  remix-cache:
  remix-public-build:
